name: nlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2
  - scikit-learn
  - pip
  - psutil
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - "jax[cuda12_pip]==0.4.20"
    - "jaxlib[cuda12_pip]==0.4.20"
    - regex
