name: nlp
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scikit-learn
  - pip
  - psutil
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - "jax[cuda11_pip]"
    - regex
